/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ExplenationSign: typeof import('./components/ExplenationSign.vue')['default']
    InfoSign: typeof import('./components/InfoSign.vue')['default']
    MeDescription: typeof import('./components/MeDescription.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    PageSwitcher: typeof import('./components/PageSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Unlock: typeof import('./components/Unlock.vue')['default']
    WelcomeSign: typeof import('./components/WelcomeSign.vue')['default']
  }
}
